### ISSUE TITLE
Aanmaken Respec pagina

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#1]
- Vraag voor Eric: nederlands of engels?
- Vraag voor Redmer: Apart document voor use case en functional requirements? Of alles-in-één document? 

## Doel
Dit document beschrijft de .... gebruikersprocessen, functionele specificaties, use case, het informatiemodel zelf?? Alles in één of niet?

**Comment by redmer** [comment]
Gedaan in https://github.com/Stichting-CROW/verkeersborden/commit/c8353b06f50c2cdb336632765669cbb98a7b1bae
