### ISSUE TITLE
Bestaat er een "maak pdf knop in Respec?

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#109]
Bestaat er een "maak pdf knop in Respec?

**Comment by redmer** [comment]
Er bestaat in de ReSpec-knop rechtsboven export naar HTML, XML, ePub. Je browser heeft, via Printen > Opslaan als PDF ook een PDF-exportfunctie.

**Comment by ElisabethKloren** [comment]
@redmer Hoe moeilijk is het om dat om te toveren tot een "print dit als pdf" knop voor alle respec's van crow en bim loket, zodat een niet-nerd een beetje geholpen wordt?

**Comment by redmer** [comment]
1. Voor CROW kan ik een exportknop toevoegen,
   1. of in de ReSpec-pil 
   2. of als uitvoermogelijkheid bij het genereren van een referentieversie

2. Voor BIM Loket kan dat niet, omdat dat een ander ReSpec-profiel is. 
   1. of ik voeg een `bimloket` uitgeverij toe aan de CROW-ReSpec fork.
   2. alternatief kan een webpagina zijn die een PDF genereert. 

Optie 1.2 is het makkelijkst.
Optie 2.1 is ook eenvoudig, maar heeft wel wat consideratie en input nodig wat betreft opmaakverschillen CROW vs BIM Loket.

**Comment by redmer** [comment]
In https://github.com/Stichting-CROW/respec-repo-template/releases/tag/v3.2.0 heb ik een PDF-exportfunctie toegevoegd aan de `lifecycle.yaml` automatisering. Die is nog niet beschikbaar voor Stichting-CROW/verkeersborden, maar dat komt.

**Comment by redmer** [comment]
BIM Loket is toegevoegd als imprint in ReSpec (https://github.com/Stichting-CROW/respec/releases/tag/v32.1.9) en ook in de CSS is die toegevoegd https://github.com/Stichting-CROW/respec-design/commit/5be54a62e625316192390b1e1b3c16d9e1450691

**Comment by ElisabethKloren** [comment]
Daarmee is deze issue voor nu afgesloten.

**Comment by redmer** [comment]
Nadat ik stichting-crow/respec-workflows-template#1 heb gemerged, kan in deze repo de workfllows nog toevoegen.

**Comment by redmer** [comment]
Met [96fd7a0](https://github.com/Stichting-CROW/verkeersborden/commit/96fd7a0179f776221e95eeeeb0f74230ba056892) is de [lifecycle](https://github.com/Stichting-CROW/verkeersborden/actions/workflows/lifecycle.yaml) knop beschikbaar gekomen.

Ik heb 'm ook uitgetest, natuurlijk.
- https://docs.crow.nl/verkeersborden/v/framework@IR-20220609/ is de referentieversie, op het moment van de build aan te geven of je comments wil via Hypothes.is of e-mail. (Ik heb geen van beide aangeklikt).
- https://docs.crow.nl/verkeersborden/v/framework@IR-20220609/framework@IR-20220609.pdf is de verwerkte PDF.
