### ISSUE TITLE
Hoe kan ik zorgen dat afbeeldingen schalen?

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#133]
Bij het weergeven van de afbeeldingen in de respec, vallen ze vaak buiten beeld. Hoe kan je zorgen dat de afbeeldingen meeschalen met de breedte van de tekst?

**Comment by redmer** [comment]
Ik heb een afbeelding (waarvan de link niet juist was) gewijzigd en meteen ook de breedte-opmaak toegepast in https://github.com/Stichting-CROW/verkeersborden/commit/ff1ad539d809ed616d4e72d3771c54f45c69982e#diff-55f0f8e54b43b5a6a2b780de68d29e47f16ced7478503aca7980301e22ddca02R16-R19.

Een directe `img`, al dan niet via Markdown (`![]()`) is nooit beperkt in de breedte. Door dat binnen een `<figure>` te plaatsen, wordt het wel in de breedte beperkt, en kun je ook met `<figcaption>` een bijschrift toevoegen.

Voor de andere afbeeldingen heb ik dat nog niet gedaan.
