### ISSUE TITLE
Definities in de tekst

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#137]
Voor de leesbaarheid is het toich handiger om definities op te nemen in de tekst. Kan het document ook een lijst met "in de tekst gedefinieerde begrippen" krijgen, naar de begrippen in in de index staan?

**Comment by redmer** [comment]
Je kunt elke term bij eerste gebruik met `<dfn></dfn>` definiëren, om dan met `<section id="index></section>` een lijst te genereren in index.html.

**Comment by ElisabethKloren** [comment]
verwerkt
