### ISSUE TITLE
eisen uit Respec halen

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#144]
In het architectuur framework heb ik eisen gezet aan het informatiemodel, te herkennen aan de tekst MOET

Kun je die op een of andere manier ook in een overzicht zetten?

**Comment by redmer** [comment]
Met [da3819b](https://github.com/Stichting-CROW/verkeersborden/commit/da3819b3271e815781dcf8559f06ec38ff1940c9) heb ik dit toegevoegd aan de bijlages.

Als het naar wens werkt, kunnen we het overwegen op te nemen in ReSpec.
