### ISSUE TITLE
Eisen aan visualisaties 

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#155]
Aan welke eisen moeten de gevisualiseerde borden voldoen? Te denken valt aan:

- Lettertype?
- Contrasten?
- Minimaal Letterformaat
- RAL-kleuren?

**Comment by elsrijnierse** [comment]
dit zijn denk ik wel de dingen waar je eisen voor moet opstellen, maar de inhoud van die eisen moet een kenner van web/mobile  gui ontwerp zich mee bezig houden
is standaard maat ook nog iets? SVG is wel scalable, maar  hoe ver kun je in zoomen en uitzoomen , ik heb niet genoeg verstand van SVG
in de visualisatie/het standaard plaatje  ook aandacht voor de kleurenblinde weggebruiker, daar zijn allerleii andere kleuren schema's voor, tenminste elk plaatje in een volledig grijsschema aan bieden

**Comment by ElisabethKloren** [comment]
1) ok, ik ga hier eisen voor opstellen
2) SVG geeft schaalbaarheid, dus maatvoering is minder relevant (een letter wordt bewaard als letter, een cirkel als cirkel)
3) Extra eis opgenomen
