### ISSUE TITLE
Onverplicht fietspad

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#157]
Els zegt: Het onverplichte fietspad (dat verboden is voor brommers) is een zwarte rechthoek met het woord fietspad erin en kent voor zover ik weet geen einde bord

Is er een aanvulling / wijziging ten opzichte van de RVV1990 die ik niet ken?

**Comment by elsrijnierse** [comment]
ik denk het niet maar in de fysiek werkelijkheid is dit zwarte bord heel vaak nog wel aanwezig, hoewel het dus kennelijk niet meer in de RVV staat.
en is in elk geval de variant zwart met een streep erdoor niet aanwezig. (vraag me ook of of blauw met een streer erdoor consequent aanwezig is ik puzzel dat even uit)

**Comment by elsrijnierse** [comment]
wat  ik al dacht
in de provincie gr fr dr ov gl fl en nh samen zijn: 
10051 G13 borden
en maar 1078 G14 borden

46832 G11 borden
en  maar 2694 G12 borden

29289 G12a borden
en maar 2463 G12b borden


voor autowegen is er ook verschil maar toch iets minder desastreus:
1155 G3 borden
677 G4 borden (dit kan nog verklaard worden doordat G4 borden vaak maar op een kant van de weg staan)

**Comment by ElisabethKloren** [comment]
Ik ga voor nu deze issue sluiten; we modelleren eerst de actuele borden in de RVV 1990, dan bepalen we in de ontwikkelfase of oudere borden ook moeten worden opgenomen, of dat de verkeerskundige informatie de nieuwe borden bevat
