### ISSUE TITLE
Twee verkeersregels maximum snelheid?

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#158]
Vraag is, wat is het voor de SMART Mobility systemen beter geschikt:

OPTIE 1: De [=standaard wettelijke maximumsnelheid=] via het [=RVV1990-WegType=]/[=RVV1990-RijbaanType=]/[=RVV1990-InrichtingsType=] vinden, en daarnaast eventueel een  [=lokale wettelijke maximumsnelheid=].

OPTIE 2: In de verkeerskundige informatie wordt altijd de [=standaard wettelijke maximumsnelheid=] aangeduid, en daarnaast eventueel een  [=lokale wettelijke maximumsnelheid=].

OPTIE 3:  In de verkeerskundige informatie wordt de [=wettelijke maximumsnelheid=] opgenomen. Omdat er meer algemene verkeersregels gelden, moet echter sowieso het [=RVV1990-WegType=] worden aangeduid. Denk bijvoorbeeld aan de regel, dat men op een autosnelweg niet mag stilstaan. Het opnemen van de [=wettelijke maximumsnelheid=] is als alleen een [=standaard wettelijke maximumsnelheid=] geldt dubbele informatie, met ook nog eens kans op tegenstrijdigheden.

**Comment by A-de-Jong-3M** [comment]
wat wanneer het een tijdelijke situatie betreft (Werk in Uitvoering)?

**Comment by ElisabethKloren** [comment]
dubbel met #165
