### ISSUE TITLE
Bordlocatie: lengterichting in meters of % van het wegvak

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#160]
Check waarom Els denkt dat het laatste wellicht beter is?

**Comment by elsrijnierse** [comment]
vanuit oogpunt van het doel van het model (de weggebruiker/leverancier van diensten aan de weggebruiker is  een relatie met het netwerk essentieel, maar ik denk dat het  en en moet zijn, dus  ook de xy

vanuit de weggebruiker gezien is meters logischer en begrijpelijker, maar bij correcties van de geometrie van een wegvak (of bij  intekenen van borden met behulp van xy op een andere kaart dan het NWB) leidt % tot nauwkeuriger informatie.

**Comment by ElisabethKloren** [comment]
Ik heb even alle opties opengelaten
