### ISSUE TITLE
Voorstel OG:  wettelijke maximumsnelheid opnemen via wegtypering én via afwijkende lokale snelheid, met twee verkeersregels

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#165]
Voorstel aan opdrachtgever om in de eerste versie van het informatiemodel uit te gaan van optie 1, het opgeven van minimaal het type wegvak waaruit de wettelijke snelheid kan worden afgeleid: in het informatiemodel heeft dit type wegvak al een specifieke snelheid. 
<img width="778" alt="standaardwetmaxsnelheid" src="https://github.com/Stichting-CROW/verkeersborden/assets/48585720/4c186b4e-9002-486f-b378-c1cfd295b1f6">

Daarnaast kan men een lokale afwijkende snelheid opgeven

Deze informatie kan men niet volledig uit de huidige ndw dataset halen op basis van zones , want [de wet](https://wetten.overheid.nl/jci1.3:c:BWBR0004825&hoofdstuk=II&paragraaf=8&artikel=22a&z=2023-07-01&g=2023-07-01) vraagt ook welke weginrichtingstype het betreft

"**wettelijke maximumsnelheid**", de hoogste snelheid die op een (gedeelte van een) weg is toegestaan voor een voertuigtype
"**standaard wettelijke maximumsnelheid**","De standaard wettelijke maximumsnelheid is de hoogste snelheid die op een wegvak is toegestaan of op een bepaald gedeelte van een wegvak is toegestaan op basis van de RVV 1990 § 8. Maximumsnelheid. De standaard wettelijke maximumsnelheid is afhankelijk van het wegtype, het rijbaantype en het voertuigtype" 
"**lokale wettelijke maximumsnelheid**",een lokaal toegestane maximumsnelheid die afwijkt van de standaard wettelijke maximumsnelheid op het betreffende wegtype of rijbaantype"

Openstaande vraag, wat is voor de datagebruikers (SMART Mobility fabrikanten) en dataopstellers (verkeerskundigen/NDW) beter werkbaar: 

OPTIE 1: Nadeel: complexe afleiding van de gewenste snelheid, die wel met query's kan worden ondersteund. Voordeel: de wegbeheerder legt meer informatie vast over de weg en kan controleren of de weginrichting klopt met de toegestane snelheid volgens de borden.
OPTIE 2: Nadeel: de informatie wordt dubbel aangeboden en kan tegenstrijdig zijn
OPTIE 3: Nadeel: een fout bij het opstellen van de informatie kan niet goed worden gevonden, omdat het een lokale maximum snelheid kan betreffen of gewoon een fout; eventueel kan de fout worden gevonden via de afwezigheid van een verkeersbord.

**Comment by A-de-Jong-3M** [comment]
wat wanneer de hoofdrijbaan en de parallelrijbaan verschillende snelheden hebben - positie van verkeerstekens / rotatie van verkeerstekens?

**Comment by ElisabethKloren** [comment]
Ja, de geldigheid van een verkeersregel/bord kán worden beperkt tot één rijbaan, dat wordt in het model geregeld.

**Comment by ElisabethKloren** [comment]
plus nog toevoegen: wat wanneer het een tijdelijke situatie betreft (Werk in Uitvoering)?

**Comment by ElisabethKloren** [comment]
Besluit 2024-05-17: Akkoord met scheiding tussen fysiek en functioneel voorkomen.
