### ISSUE TITLE
Functioneel kenmerk versus fysiek bord

### ISSUE THREAD

**Issue by ElisabethDeVries** [Stichting-CROW/verkeersborden#18]
Verkeerskundige ontwerpt een eenrichtingsverkeer; fysieke representatie zijn een of meer verkeersborden (naar de weggebruiker); zou in de toekomst een beperking kunnen zijn op de rijrichting tussen twee kruispunten

Snelheidsverandering kan gebeuren zonder verkeersbord, bijvoorbeeld door verkeersregels (wegtype veranderdt; of bij kruispunt; of je rijdt de kom in);

**Comment by ElisabethKloren** [comment]
verwerkt in de tekst
