### ISSUE TITLE
Relatie tussen verkeersregel/bord en NWB-wegvak, rijrichting en rijstrook in het informatiemodel?

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#197]
Een verkeersregel hangen niet zomaar in de lucht, deze geldt voor:

- [ ] Relatie verkeersregel met wegvak opnemen in informatiemodel
- [ ] Beperking werking verkeersregel in één rijrichting opnemen in informatiemodel
- [ ] Beperking werking verkeersregel tot Eén of meerdere rijstroken opnemen in informatiemodel
- [ ] Beperking werking verkeersregel tot een gedeelte van het wegvak  opnemen in informatiemodel
- [ ] Locatie bord aanduiden in informatiemodel
- [ ] Richting van bord opnemen in informatiemodel? Of is dit geregeld van link met verkeersregel die geldt voor een bepaalde richting? Nee, want kan dwars op de weg staan

- NB: bij de fysieke borden worden OB401 en specifieke lengtes opgenomen, los van de verkeersregel die ook een werkingslengte heeft

NB bij NDW hebben ze dit in de documentatie staan: https://docs.ndw.nu/locatiereferentie/

Eenzelfde vraag voor verkeersbord: dat staat op een bepaalde locatie, maar is bedoeld voor één rijrichting en eventueel alleen voor één strook > hiervoor aparte issue ma

Aanname: we hoeven geen onderscheid te maken tussen rijbaan en NWB-wegvak Of is er bij een fysieke afscheiding tussen twee rijstroken altijd sprake van één NWB-wegvak, en hoeven we dus geen definitie van rijbaan op te nemen in het informatiemodel?

**Comment by bbussink** [comment]
Verkeersborden zijn aan het NWB gekoppeld en (binnenkort) verrijkt met rijrichting en fractie. Dit stelt gebruikers in staat om te bepalen welk deel van de weg of wegen welke verkeersregel van toepassing is

Hierbij zijn de volgende 3 kolommen van belang
1. **wvk_id**: Op welk wegvak heeft het bord betrekking, bijvoorbeeld wvk_id 1234
2. **drivingDirection**: Heen, Terug of Loodrecht. Het bord heeft betrekking op de Terug richting
3. **fraction**: bord staat 0.412134 van de lijn 

Stel je hebt op een wegvak meerdere snelheidsborden dan kun je met bovenstaande variabelen bepalen welke snelheid van toepassing is op welk subdeel van een wegvak.

Verwijzing naar de kolomnamen: https://docs.ndw.nu/data-uitwisseling/interface-beschrijvingen/verkeersborden-api/

**Comment by ElisabethKloren** [comment]
info uit george verwerkt; opvolging van deze issue zie #325
