### ISSUE TITLE
Hoek verkeersbord tov wegvak

### ISSUE THREAD

**Issue by ElisabethDeVries** [Stichting-CROW/verkeersborden#202]
Moet de hoek van het verkeersbord tov het wegvak worden aangeduid? Normaal is het haaks op de rijrichting, maar het E4 bord kan ook parallel staan zodat je vanaf de andere rijrichting ook kan zien dat je niet mag parkeren

In George zag ik volgens mij meer een kijkrichting in 360 graden, maar is dat wenselijk?)

& Check in Datex?

**Comment by A-de-Jong-3M** [comment]
Eigenlijk wel, de rotatiehoek verkleind het oopervlak van een verkeersbord en maakt het daardoor minder zichtbaar. De invalshoek van licht bepaald ook de mate van reflectie en daarmee de zichtbaarheid. de zichtbaarheid van verkeersborden is opgenomen in o.a. de EN12899, DIN67520 en EN3381 in dit specifieke voorbeeld gaat het dan om de invalshoek. In geval van parkeren kan, zowel met als zonder een onderbord, haaks op de rijrichting staan.

**Comment by ElisabethKloren** [comment]
De vraag is, wat we moeten toestaan qua input. In George kan nu dus een hoek van 0 - 360 worden opgegeven lijkt het, dat is realistisch (het kan allemaal voorkomen als je de situatie buiten meet, inclusief verdraaide en aangereden borden), of moet je hier de gewenste/geplande richting aanduiden? Dan is het of parallel of haaks op de rijrichting? > dit moet ik nog checken bij vakinhoudelijke collega's

**Comment by bbussink** [comment]
In het datamodel van de verkeersborden is recent (vanaf api v3) ook een kolom toegevoegd met de driving_direction'. Deze gaat de waardes Heen, Terug of Loodrecht `bevatten. Heen en Terug verwijst naar de richting van het wvk_id waar het betrekking op heeft. Deze kolom wordt binnenkort gevuld.

Daarnaast is er in v3 ook een kolom 'nenTurningDirection' opgenomen.

**Comment by ElisabethKloren** [comment]
Zowel de hoek als de richting worden opgenomen in het informatiemodel.

**Comment by gulaycanbaloglu** [comment]
An aspect with two different qualification groups is created and linked to the network location of fysieke plaat, and verkeersmaatregel.
Refer #339 for more info on this decision.
