### ISSUE TITLE
Onderbord: Bord geldig na x meter

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#217]
Voorkomen in ndw verkeersbordendatabase:
na 100 m	263	0.01	
na 50 m	252	0.01	
na 150 m	198	0.01	
na 200 m	108	0.01	
na 300 m	63	0.00	
na 30 m	59	0.00
na 50 m; uitgezonderd	58	0.00

**Comment by bbussink** [comment]
In George is het nu mogelijk om onderborden een label te geven, zoals vooraankondiging.
Veel onderborden met een vooraankondiging hebben nu een label gekregen de verkeersborden data:
De onderstaande tekst komt uit de CSV v3 API voor bord met ndwid: 005c9f1d-0fed-4f47-a8bf-60c1849458b6.
`"100 m (VOOR)"`

Het betreft dit specifieke voorbeeld: https://wegkenmerken.ndw.nu/verkeersborden/005c9f1d-0fed-4f47-a8bf-60c1849458b6

Aangezien het een vooraankondiging betreft heeft het bord mijn inziens geen werkingslengte, het is immers een vooraankondiging. Verderop staat het definitieve verkeersbord en dat heeft een werkingslengte in mijn beleving

**Comment by ElisabethKloren** [comment]
interessant voorbeeld, want op andere plekken / in andere context betekent 100 m dat het bord 100 meter lang geldt, bijvoorbeeld een bord 90 k/m  met onderbord "200m; bij nat wegdek" betekent dat je 200 meter lang 90 km / h moet rijden, als het wegdek nat is (sic). Dan is het geen vooraankondiging, maar een werkingslengte. 
Het bord op het voorbeeld zegt dat er over 100 m een rotonde komt; in dat geval is er ook nog een rotondebord ter plaatse; maar bij andere borden is er alleen een vooraankondiging. 

Dus er komt een onderbord voor werkingslengte (#216 ) en op basis van deze issue: een onderbord vooraankondiging, waarbij er varianten bestaan met "100m" en "na 100 m"

De verkeersregel is pas 100 meter verderop aan het wegvak gekoppelt en krijgt geen vooraankondiging

**Comment by ElisabethKloren** [comment]
opgenomen in de lijst met onderborden
