### ISSUE TITLE
Ter besluit OG: Afwijking op uitgangspunten architectuur framework; alle voorkomende snelheden toestaan

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#245]
In het architectuur framework is als uitgangspunt opgeschreven alleen de wettelijk toegestane snelheden kunnen meegeven. 

Uitgangspunt bij de opdracht van het informatiemodel is geworden: alle voorkomende borden kunnen aanleveren. Daarbij wel voorkomen, dat er echt rare dingen worden ingevuld (11 km/h)

**Voorstel: in het informatiemodel uitgaan van de totale lijst met voorkomende snelheden in het bordenbestand**

Makkelijk zat om bij het aanleveren van nieuwe borden een waarschuwing in te bouwen voor het opgeven van een fantasiesnelheid.

Bij akkoord: 
- [ ] Update architectuur framework nodig. 
- [ ] Opstellen voorbeeld dataset met alle voorkomende snelheden\
- [ ] Opstellen SHACL waarin een foutmelding ontstaat "u heeft een niet in de RVV voorkomende snelheid gebruikt"

**Comment by ElisabethKloren** [comment]
wettelijk genoemde snelheden in het rvv: 
Snelheid
15
30
50
60
70
80
90
100
110
120
130

**Comment by ElisabethKloren** [comment]
dat betekent dat de niet-wettelijke snelheden 5, 10, 20, 25, en 40 worden toegestaan in het informatiemodel

**Comment by bbussink** [comment]
Het klopt dat er nu borden op straat staan met snelheden die niet in conform BABW zijn ( https://wetten.overheid.nl/jci1.3:c:BWBR0009104&hoofdstuk=II&paragraaf=4&z=2023-10-01&g=2023-10-01 ).

Waarom nu wel de snelheden meenemen die nu 'niet-wettelijk' worden gebruikt en niet de snelheden toestaan die nu nog niet worden gebruikt maar ook 'niet-wettelijk' zijn? Dus waarom wel 25 en 40 meenemen en niet 35, 36, 37?

Je zou er ook voor kunnen kiezen om alle snelheden tussen de 0 t/m 130 toe te staan. in het data-model en de niet wettelijke snelheden dan markeren als exceptie.

**Comment by ElisabethKloren** [comment]
opties maximumsnelheden, dit was het uitgangspunt bij het opstellen van het architectuur-framework in 2023:
Optie 1: Moet het informatiemodel een beperkte lijst geven met de snelheden die je kunt gebruiken? Dit geeft als nadeel dat je met de wet mee moet bewegen en de lijst aanpassen als de wet wijzigt.
Optie 2: Je kunt alle gehele getallen gebruiken die je wilt. Dit geeft als nadeel dat een wegbeheerder fantasiesnelheden op kan geven die niet gehandhaafd kunnen worden en onduidelijkheid bij de weggebruiker geven.
Optie 3: Optie twee, maar je maakt een automatische controle erbij om te checken of het getal klopt met de snelheid die je volgens de wet mag aangeven. Die gebruik je bij het valideren van een dataset. Dan kan in elk geval niet per ongeluk een verkeerde waarde worden ingevuld. Omdat het doel van het informatiemodel is, om verkeerskundige informatie op basis van de wet te kunnen publiceren, is gekozen voor optie 1.

**Comment by ElisabethKloren** [comment]
aanname bij opstellen van het concept: het aspect krijgt een waarde mee zonder lijst (optie 2 in bovengenoemde); bij de signs worden de meest voorkomende snelheden, ook de niet-wettelijke, uitgewerkt om standaard fysieke platen te kunnen opstellen en te mappen met NLCS

In datachecks kan worden ingebouwd dat  niet-wettelijke waarden een foutmelding geven. Dat hoeft niet in het informatiemodel
