### ISSUE TITLE
Verkeersregel: alleen deel kalenderjaar, en andere afwijkende borden

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#29]
Te dataficeren: 
- gedurende een of meer beperkte periode (jaarlijks), voorbeeld van 1 mei tot 1 september

Varianten die niet gemodelleerd worden:
- bij schemering en duisternis > variabel
- "schoolopening en sluitingstijden"
- gedurende een of meer beperkte periode (eenmalig) (bijvoorbeeld najaar; broedseizoen)
- uitzoeken of er meer varianten zijn
- bovenstaande kunnen op gecombineerd voorkomen

@redmer zijn hier al internationaal standaarden voor? zijn er voor tijdsperioden al standaarden? 
Is bovenstaand verhaal voldoende om een uitgangspunt te formuleren voor het informatiemodel?

**Comment by redmer** [comment]
[rfc3339](https://www.rfc-editor.org/rfc/rfc3339) is een subset van ISO 8601, die vaste tijden elke dag wel zou kunnen aangeven. Dat is dus eigenlijk bijna niks. 

@EricVanGorkom ben jij bekend met standaarden voor dergelijke tijdsperioden, bijv. voor tijdsschakelingen van verlichting?

**Comment by EricVanGorkom** [comment]
@redmer Vanuit licht wordt het schakelen voor dit soort dagen/perioden meestal vanuit een hoofdpost geregeld -> staat op een centrale computer en het geautomatiseerd bepalen wat voor "speciale" dag het is, is in de meeste gevallen gewoon handwerk (dus inkloppen). Een internationale standaard ervoor lijkt me ook wat lastig - de behoeften verschillen teveel.

**Comment by ElisabethKloren** [comment]
ik heb zoiets bedacht: Startdatum,Geldigheid van verkeersregel op specifieke kalenderdagen beginnend bij de startdatum,Startdatum,time,xsd:gMonthDay,,standaard wettelijke maximumsnelheid,lokale wettelijke maximumsnelheid,adviessnelheid,,,,
Einddatum,Geldigheid van verkeersregel op specifieke kalenderdagen eindigend op de einddatum,Einddatum,time,xsd:gMonthDay,,standaard wettelijke maximumsnelheid,lokale wettelijke maximumsnelheid,adviessnelheid,,,,
