### ISSUE TITLE
Check in Datex II: kun je de ingangsdatum en eventueel einddatum van de verkeersmaatregel / plaatsing bord daarin aangeven?

### ISSUE THREAD

**Issue by ElisabethDeVries** [Stichting-CROW/verkeersborden#295]
Doel 1: voorafgaand aan ingang van de geldigheid van een nieuwe verkeersmaatregel of bord al data kunnen leveren

Doel 2: : Tijdelijke verkeersborden kunnen aanmelden

**Comment by werkenr** [comment]
Middels de TrafficRegulationOrder is er een validity op te geven, waarmee aan te geven is wanneer een maatregel van kracht is:
https://docs.datex2.eu/_static/data/v3.5/umlmodel/html/EARoot/EA3/EA8/EA1/EA1/EA1292.htm

**Comment by ElisabethKloren** [comment]
@gulaycanbaloglu dit moeten we even bespreken, als je in Datex kijkt dan gebeurt daar al heel veel > moet de geldigheid van-tot toch een aspect worden, om aan te kunnen geven dat dit een date/time veld is?

**Comment by ElisabethKloren** [comment]
En ik zie dat bij NDW vier datums worden meegegeven, geen idee waarom want in theorie komen de datums overeen: Verwijderd op: wanneer je een status verwijderd hebt kun je hier de datum van vandaag of eerder plaatsen
Geplaatst op: status geplaatst met een datum van vandaag of eerder
Beoogde plaatsing: is een datum in de toekomst
Beoogde verwijdering: datum van verwijdering in de toekomst


Dit heeft ook te maken met status: Voor 'status'  moet in de huidige dataset bij het ndw gekozen worden voor de waarden: 'PLANNED', 'PLACED' of 'REMOVED'.

Als we de status toevoegen in het informatiemodel, is maar 1x een start- en einddatum nodig, ik denk dat dit anders werkt door de gebruikte geo-distributietechniek

**Comment by gulaycanbaloglu** [comment]
I think the start and end date will suffice for the regulation, but while the regulation is active the road signs might be replaced which might be relevant information to store. We can capture this information by introducing an aspect called PlaatsingStatus with the enumeration list: planned, placed and removed.
