### ISSUE TITLE
Vanuit alle ReSpec's één bronbestand met definities gebruiken

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#319]

**Comment by redmer** [comment]
In https://github.com/Stichting-CROW/verkeersborden/commit/1127b016a8fed2dc5dd46282bb989cbfe463c97f uitgevoerd.

Ik heb de definities in één bestand gezet en de alledefinities-bestanden uit "definitielijst", "framework", "howtodatamangement", "technicaldocs" verwijderd en in hun index.html naar het ene bestand laten verwijzen
