### ISSUE TITLE
draairichting/bearing van een bord nodig voor de geometrische representaties van de verkeersborden

### ISSUE THREAD

**Issue by ElisabethDeVries** [Stichting-CROW/verkeersborden#339]
cf ndw: De geo-oriëntatie van de leeszijde van de fysieke plaat in graden met de richting  ten opzichte van het geografische noorden.

even checken of ik dit als aspect op de juioste manier heb neergezet in de beheeromgeving

**Comment by gulaycanbaloglu** [comment]
#202 These two issues seem like not supporting each other. Do we want degrees of alignment of fysieke plaat, or a list of values like Heen, Terug of Loodrecht? Is the reference direction north or the direction of the road? Taking the direction of the road as 0, and representing bearing as an angle makes more sense to me.

**Comment by gulaycanbaloglu** [comment]
Decision: two different aspects called richting (bearing) and rijrichting (driving direction). Richting is the angle with unit degree, rijrichting is the enumeration for heen, terug (and loodrecht).
