### ISSUE TITLE
Uitwerken aspect snelheid 

### ISSUE THREAD

**Issue by ElisabethDeVries** [Stichting-CROW/verkeersborden#341]
snelheid als aspect met unit km/h en 

snelheden van de volgende signs uitgewerkt::

5
10
15
20
25 > niet, deze komt niet voor in IMBOR en ook niet in NLCS
30
40 > niet, deze komt niet voor in IMBOR en ook niet in NLCS
50
60
70
80
90
100
120
130

**Comment by gerritversteegh** [comment]
@gulaycanbaloglu

**Comment by ElisabethKloren** [comment]
correctie; het aspect wordt gewoon een geheel getal (integer)

we moeten even bespreken of "adviessnelheid" niet een verkeersmaatregel is, het aspect snelheid geldt in meerdere gevallen
