### ISSUE TITLE
uitwerken aspect: voertuigtype

### ISSUE THREAD

**Issue by ElisabethDeVries** [Stichting-CROW/verkeersborden#342]
volgens deze beschrijving zijn er 4 varianten/:  https://docs.crow.nl/verkeersborden/howtodatamanagement/#voertuigtypen

**Comment by gerritversteegh** [comment]
@gulaycanbaloglu

**Comment by ElisabethDeVries** [comment]
O ja, en dan nog de vraag > een verkeersmaatregel kan wel of niet van toepassing zijn op meerdere voertuigtypes, dus wellicht is een enumeratie hier niet de oplossing?

**Comment by ElisabethDeVries** [comment]
dat kan wel, via de cardinaliteit
