### ISSUE TITLE
kunnen we aanduiden welke aspecten verplicht zijn bij een verkeersmaatregel, en welke optioneel?

### ISSUE THREAD

**Issue by ElisabethDeVries** [Stichting-CROW/verkeersborden#346]
vooruitlopend op de controle van een dataset, kunnen we aangeven welke aspecten verplicht zijn bij een verkeersmaatregel, en welke optioneel?

**Comment by gulaycanbaloglu** [comment]
We can add an information attribute (i.e., isRequired -> Yes/No) to aspects?

**Comment by ElisabethDeVries** [comment]
After discussion, we use cardinaliteit, example: 0:1, 1:1, 1:n

**Comment by gulaycanbaloglu** [comment]
Actually we can add cardinalities under shape tab in an aspect.
