### ISSUE TITLE
Definieer "architectuur framework"

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#46]
Wat is een architectuur framework?

**Comment by mickbaggen** [comment]
Zie bijvoorbeeld https://rws.begrippenxl.nl/ABDL/nl/page/DEF-0203.

**Comment by ElisabethKloren** [comment]
Top, inmiddels is dit issue opgelost door beter te beschrijven wat de inhoud is van dit document.
