### ISSUE TITLE
Referentie opnemen naar plan voor bouw van een database verkeersbesluiten

### ISSUE THREAD

**Issue by ElisabethDeVries** [Stichting-CROW/verkeersborden#5]
Is/zijn er al databases? Wat zijn die en wat staat daar in?

**Comment by ElisabethKloren** [comment]
Programma Netwerkregistratie https://dutchmobilityinnovations.com/spaces/1270/programma-netwerkregistratie/landing

**Comment by ElisabethKloren** [comment]
verwerkt in  de tekst
