### ISSUE TITLE
Grafische weergaven, afbeeldingen van verkeersborden

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#60]
Onderdeel van het informatiemodel

Welk formaat is nodig? .. heeft drie formaten: jpg, pdf, svg, (schaalbaar formaat > dus svg zou tof zijn)

Opnemen in scope

**Comment by redmer** [comment]
Een paar jaar geleden is er zo'n contrastrand aan verkeersborden toegevoegd, een smalle witte bies om de bord-rand duidelijker te maken. Maar dat staat niet in de Bijlage 1 van RVV. Waar is dat dan officieel gemaakt?

**Comment by ElisabethKloren** [comment]
Ik ben even uitgegaan van de <a href=https://wetten.overheid.nl/jci1.3:c:BWBR0009104&hoofdstuk=II&paragraaf=3&z=2012-07-01&g=2012-07-01">Uitvoeringsvoorschriften BABW inzake verkeerstekens</a>, die verwijzen weer naar de NEN-norm. Daarnaast is svg opgenomen als aanname
