### ISSUE TITLE
Wie is formeel bronhouder van de wettelijk toegestane verkeersborden

### ISSUE THREAD

**Issue by ArnoldDekker** [Stichting-CROW/verkeersborden#66]
In hoofdstuk https://docs.crow.nl/verkeersborden/framework/#verkeersborden wordt aangegeven, dat alle verkeersborden in scope zijn. De vraag is: wie is formeel bronhouder van deze verkeersborden? Wie beheert deze en mag mutaties doorvoeren? 

Verder wordt er gesproken over onderborden, die door wegbeheerders deels zelf kunnen worden onderhouden. Hoe zit dat dan precies. Blijkbaar is een deel van de onderborden generiek en beschikbaar voor alle wegbeheerders. Maar een deel is maatwerk mogelijk, per wegbeheerder te configureren. Hoe zit dat dan tav bronhouderschap over deze informatie?

**Comment by ElisabethKloren** [comment]
Na overleg met Els besloten dat we alleen een formele lijst met borden en onderborden aanhouden (eventueel met een optie om een vrije tekst in te vullen bij een onderbord)
