### ISSUE TITLE
Eisteksten komen in inhoudsopgave

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#67]
@redmer help me even in uitgangspunten.md heb ik gebprobeerd om eisen te formuleren, nu komen die in de inhoudsopgave in ReSpec. Wat is fout aan mijn code?

<section>
  <h2>Informatiemodellering<h2>
  <p> <ul> <li> Het informatiemodel MOET worden opgesteld conform de regels voor semantisch modelleren en met de relaties en concepten in de NEN 2660:2021. </li>
<li> Het informatiemodel MOET waar mogelijk aangesloten op de NEN 3610 en de MIM. Bij tegenstrijdigheden geldt de NEN 2660. </li>
<li> Het informatiemodel MOET generiek en schaalbaar zijn, zodat de relatie met andere use cases in de toekomst goed te leggen valt.  </li>
<li> Het informatiemodel MOET van alle concepten een definite geven of verwijzen naar een definitie in wetten of andere informatiemodellen. </li></ul></p>
</section>
<section id="conformance"></section>

**Comment by redmer** [comment]
https://github.com/Stichting-CROW/verkeersborden/commit/810624d230e2f778cbf465299b1f89c5c9e363a0#diff-494b5900e0bc33d2d0330038649d809572a5e56ea8d6722444b0957a04e78aad

het waren de sluittekens. 

https://github.com/Stichting-CROW/verkeersborden/blob/main/docs/framework/hoofdstukken/uitgangspunten.md?plain=1#L4-L19

Dat van de conformance hier lijkt me ook gek geplaatst?

**Comment by ElisabethKloren** [comment]
Ok, dit document stelt eisen aan het informatiemodel > daar in conformance toch voor, om te beschrijven aan welke eisen het model moet voldoen? 

Straks komt erveen document met eisen aan de data die je modelleert conform het model, dan zijn de eisen daar van toepassing./

Of is conformance voor iets anders bedoeld?
