### ISSUE TITLE
Foutmelding in Respec

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#68]
nog zo'n kleintje, de laatste foutmelding in respec: Linter (no-headingless-sections): Alle secties moeten beginnen met een h2-6 element. Voeg een h2-6 toe aan de conflicterende sectie of gebruik een <div>. Zie de developer console. Occured at: 1, 2, 3.****

**Comment by redmer** [comment]
Opgelost in 0abc68a
