### ISSUE TITLE
paragraaf 2.1.1

### ISSUE THREAD

**Issue by elsrijnierse** [Stichting-CROW/verkeersborden#71]
in paragraaf 2.1.1 is de stelling dat het ontbreekt aan verkeerskundige kenmerken in NWB/WEGGEG./WKD een stapje te boud, snelheid, is een verkeerskundig kenmerk, toegestane rijrichting ook, en er zijn er denk ik nog een paar

**Comment by ElisabethKloren** [comment]
verwerkt
