### ISSUE TITLE
verstandig? paragraaf 2.4.4

### ISSUE THREAD

**Issue by elsrijnierse** [Stichting-CROW/verkeersborden#72]
Als je alle ook door de wegbeheerder bedachte niet RVV borden in scope  haalt, dan generere je in potentie wild groep, ik denk niet dat je dat moet doen. Als een wegbeheerer een verkeersbesluit neemt moet hi dat doen met een RVV bord en niet met een eigen fantasie bord

**Comment by ElisabethKloren** [comment]
Verwerkt
