### ISSUE TITLE
Publiceren van verkeersbesluit in de decentrale bladen ipv staatscourant

### ISSUE THREAD

**Issue by ArnoldDekker** [Stichting-CROW/verkeersborden#73]
In hoofdstuk 2.1.2 Gebreken wordt het volgende aangegeven:

"Wegbeheerders zijn wettelijk verplicht om verkeersbesluiten digitaal te publiceren in de Staatscourant en deze officieel bekend te maken op www.overheid.nl. "

Met het inwerkingtreden van de Wet Elektronische Publicaties per 01072021 is dat niet meer alleen in de Staatscourant, maar ook in de decentrale bladen. Dus de tekst moet worden:

"Wegbeheerders zijn per 01072021 wettelijk verplicht om verkeersbesluiten digitaal te publiceren in de decentrale bladen zoals het Gemeenteblad, Provinciaal Blad, Waterschapsblad of Staatscourant en deze officieel bekend te maken op www.overheid.nl. "

Zie bv alle gepubliceerde besluiten sinds 01072021:

https://zoek.officielebekendmakingen.nl/resultaten?q=(c.product-area==%22officielepublicaties%22)and(dt.available%253e=%222021-07-01%22)and(dt.type==%22verkeersbesluit%20of%20-mededeling%22)and(((w.publicatienaam==%22Tractatenblad%22))or((w.publicatienaam==%22Staatsblad%22))or((w.publicatienaam==%22Staatscourant%22))or((w.publicatienaam==%22Gemeenteblad%22))or((w.publicatienaam==%22Provinciaal%20blad%22))or((w.publicatienaam==%22Waterschapsblad%22))or((w.publicatienaam==%22Blad%20gemeenschappelijke%20regeling%22)))%20AND%20w.publicatienaam==%22Staatscourant%22%20AND%20w.publicatienaam==%22Staatscourant%22&zv=&pg=10&col=AlleBekendmakingen&svel=Publicatiedatum&svol=Aflopend&rft=ds%7cStaatscourant

Vervolgens kan je bv daar verder weer filteren op specifieke kenmerken, bv de verkeersbord code.

**Comment by ElisabethKloren** [comment]
Ik heb de tekst gewijzigd, bedankt voor de correctie
