### ISSUE TITLE
Wat te doen met het concept "invloedssfeer"

### ISSUE THREAD

**Issue by ArnoldDekker** [Stichting-CROW/verkeersborden#77]
In het prototype https://verkeersbesluiten-demo.overheid.nl/demo.html geven we gebruikers we de mogelijkheid om een nieuw verkeersbord van een specifiek type te plaatsen op de kaart. Daarbij moet men dan tevens aangeven wat de invloedssfeer (reikwijdte/werkingslengte) is van dat nieuw te plaatsen bord, er zijn verschillende geometrische instrumenten mogelijk om dat aan te geven. Invloedssfeer kan men dus kunnen definiëren als de geografische locaties(s) uitgedrukt in verschillende modaliteiten, waar een verkeersbord betrekking op heeft. 

Moeten we ook nog het concept "invloedssfeer" ergens benoemen? En dan zou ik ook graag een eenduidige definitie willen en mogelijk ook een betere term: reikwijdte, werkingslengte, werkingsgebied oid?

**Comment by ElisabethKloren** [comment]
in de RVV 1990 heeft men het over een "zone"; er bestaat ook een onderbord waarop wordt aangegeven voor hoeveel meter het bord geldt. Deze twee vorobeelden in het informatiemodel als twee verschillende zaken gemodelleerd.
