### ISSUE TITLE
Opnemen verschillende definities in hoofdstuk Termen en definities

### ISSUE THREAD

**Issue by ArnoldDekker** [Stichting-CROW/verkeersborden#80]
De volgende termen moeten nog eenduidiger gedefinieerd worden:
Verkeersbesluit, verkeersbord, verkeersteken, wegmarkering, gebod en verbod, hoofdbord, onderbord, voertuigcategorie, wegbeheerder, rijstrook,

**Comment by ElisabethKloren** [comment]
ge- en verboden zijn "normaal nederlands" en definieer ik niet; andere definities opgenomen
