### ISSUE TITLE
Onderbord met 'nadere aanduiding"

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#89]
Welke "nadere aanduidingen" kunnen op een onderbord staan bij de maximum snelheid? 

> Schrijver dezes kent in elke geval de aanduiding van een specifieke dag en/of een specifiek tijdstip waarop het bord geldt. 
> Bij specifieke omstandigheden: gladheid, neerslag

Lijst met onderborden en codes: VNVF, nederlandse verkeersbordenfabrikanten. Zie het verkeersbordenboekje, en codes

**Comment by elsrijnierse** [comment]
actueel beeld verkeersborden op de NDW open data site, filteren op rvv bord code en dan de teksten op de onderborden bekijken dat is wat er feitelijk staat langs de weg

**Comment by ElisabethKloren** [comment]
@redmer ik kan het bestand vanaf https://opendata.ndw.nu/ niet openen, kun jij dit wel en mij een lijst met onderborden sturen?

**Comment by ElisabethKloren** [comment]
@elsrijnierse [verkeersborden_actueel_beeld.csv.gz](https://opendata.ndw.nu/verkeersborden_actueel_beeld.csv.gz)

**Comment by elsrijnierse** [comment]
Ok, daar heb je een GZIP uitpakker voor nodig die niet op standaard windows zit, ik heb hem wel op de RWS omgeving bijvoorbeeld, maar niet op mijn prive omgeving.


Met hartelijke groet,


Els Rijnierse
Projectleider

[NDW]

Woensdag is mijn vaste vrije dag


***@***.***

+31 (0)6 15 00 56 54

***@***.***

***@***.***

***@***.***

ndw.nu<http://www.ndw.nu/>
nationaalwegenbestand.nl

***@***.***

Volg ons op LinkedIn<https://www.linkedin.com/company/nationaal-dataportaal-wegverkeer/>





Van: Elisabeth de Vries ***@***.***>
Verzonden: dinsdag 12 juli 2022 10:00
Aan: Stichting-CROW/verkeersborden ***@***.***>
CC: Rijnierse, Els (NDW) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Stichting-CROW/verkeersborden] Onderbord met 'nadere aanduiding" (Issue #89)


@elsrijnierse<https://github.com/elsrijnierse> verkeersborden_actueel_beeld.csv.gz<https://opendata.ndw.nu/verkeersborden_actueel_beeld.csv.gz>

**Comment by ElisabethKloren** [comment]
[deze data voor a1 borden](https://github.com/Stichting-CROW/verkeersborden/blob/main/ndw_datasets/teksten%20bij%20A1%20borden.csv)

**Comment by ElisabethKloren** [comment]
De dataset is gevonden
