### ISSUE TITLE
Check wegtypes: RVV 1990, NWB en IMBOR/IMWV

### ISSUE THREAD

**Issue by ElisabethKloren** [Stichting-CROW/verkeersborden#91]
Wegtypering NWB gebruikers
Er zijn vele manieren om het Nederlands wegennet in te delen/categoriseren, waarbij vooral het indelen van dat wat niet autosnelweg of autoweg is op meer manieren gebruikelijk is. (verkeersveiligheid kent een andere indeling dan verkeersmanagement bijvoorbeeld)
Recent  is aan het NWB voor elk wegvak een typering toegevoegd, waarbij ook de typering uit TOP10 NL meegenomen is.
Lijstje dat hiervoor in overleg met de NWB gebruikers is opgesteld:
autosnelweg
autoweg
bromfietspad
erf
fietspad
lokale weg
onbekend
onverharde weg
OV-verbinding
regionale weg
ruiterpad
stadshoofdweg
straat
verzorgingsplaats
voetpad

In IMBOR/IMWV zijn óók wegtypes bedacht, vanuit oogpunt van beheer én vanuit oogpunt van netwerkberekeningen/wegontwerp: nog invullen

**Comment by elsrijnierse** [comment]
check met door NWB gebruikers bepaald wegtypering die in de maak is

**Comment by ElisabethKloren** [comment]
Ik heb een groen blok met overzichtstabel gemaakt vanuit de RVV1990-typeringen naar IMBOR en het NWB, om te laten zien dat vanuit verschillend oogpunt anders gekeken wordt naar de wegen.
