### ISSUE TITLE
zone of wegvakken coderen

### ISSUE THREAD

**Issue by elsrijnierse** [Stichting-CROW/verkeersborden#96]
aandachtspunt is dat er meerder toepassingen zijn die verschillende kaarten kunnen gebruiken .Een zone gemaakt op kaart 1  geprojecteerd op kaart twee kan ongewenste grensfouten opleveren, daarom lijkt het in eerte instantie beter om op wegvakniveau een zone te coderen

**Comment by ElisabethKloren** [comment]
verwerkt
