### ISSUE TITLE
Term verkeersinstructie niet gedefinieerd

### ISSUE THREAD

**Issue by mickbaggen** [Stichting-CROW/verkeersborden#98]
In het document "Informatiemodel verkeerstekens en verkeersbesluiten", wordt regelmatig gesproken over de term "verkeersinstructie", bijvoorbeeld in par. 6.2 (Verkeersinstructies RVV 1990). Merk echter op dat in het RVV deze term niet voorkomt. Het RVV kent wel verkeersregel, verkeersteken (onderverdeeld in verkeersbord, verkeerslicht en verkeersteken op het wegdek) en aanwijzing.

Voeg OF een definitie van de term _verkeersinstructie_ toe, inclusief een verwijzing naar de normatieve bron waar deze uit afkomstig is, OF hanteer een andere, meer gangbare term.

**Comment by ElisabethKloren** [comment]
Goed punt Mick. Ik ga de termen "verkeersregels" "verkeersadviezen" en "verkeerstekens" hanteren. Instructies worden verwijderd uit het document.
